name: Deployment
on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}

permissions:
  contents: read

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm run build
        env:
          VITE_MOBILEPAY_PHONE_VEGETABLES: ${{ secrets.VITE_MOBILEPAY_PHONE_VEGETABLES }}
          VITE_MOBILEPAY_PHONE_FOOD: ${{ secrets.VITE_MOBILEPAY_PHONE_FOOD }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=grantoftegaard
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
